# Generated by Django 3.0.4 on 2020-03-27 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_ex', '0003_auto_20200326_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='0000000', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='creator',
            field=models.CharField(default='0000000', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
