# Generated by Django 3.0.4 on 2020-05-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_test', '0002_auto_20200510_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='m_test.Project'),
        ),
    ]
